#
# Copyright (c) 2026 tutosrive. All rights reserved.
#
# Author: tutosrive
# GitHub: https://github.com/tutosrive
#
# This source code is PROPRIETARY and CONFIDENTIAL.
# Unauthorized copying, modification, or distribution of this file,
# via any medium, is strictly prohibited.
#
# This software is provided "as is", without warranty of any kind.
# In no event shall the author be liable for any claim or damages.
#
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache=true
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. For more details, visit
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
# org.gradle.parallel=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official